[tool.poetry]
name = "target-s3"
version = "1.0.7"
description = "`target-s3` is a Singer target for s3, built with the Meltano Singer SDK."
authors = ["crowemi"]
keywords = [
    "ELT",
    "s3",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
requests = "^2.25.1"
singer-sdk = "^0.44.3"
smart-open = {extras = ["s3"], version = "^7.1.0"}
fsspec = "^2025.2.0"
s3fs = "^2025.2.0"
pyarrow = "^19.0.0"
bson = "^0.5.10"

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.6"
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
target-s3 = 'target_s3.target:Targets3.cli'
